name: PR build validation check

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - develop

  workflow_dispatch:

jobs:

  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reopsitory
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Check Build Validation
        env:
          OAUTH_CLIENT_ID: ${{secrets.OAUTH_CLIENT_ID}}
          OAUTH_CLIENT_SECRET: ${{secrets.OAUTH_CLIENT_SECRET}}
        run: ./gradlew app:compileDebugSources
